/* The following code was generated by JFlex 1.4.3 on 10/14/12 11:00 PM */

import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 10/14/12 11:00 PM from the specification file
 * <tt>MipsLexer.flex</tt>
 */
class MipsLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\7\1\5\1\0\1\7\1\4\22\0\1\7\1\0\1\45"+
    "\1\10\1\14\3\0\1\43\1\44\2\0\1\41\1\2\1\16\1\0"+
    "\1\1\11\3\1\42\6\0\1\22\1\25\1\32\1\21\1\20\1\13"+
    "\1\11\1\37\1\33\1\36\1\11\1\26\1\11\1\27\1\30\1\40"+
    "\1\35\1\15\1\23\1\17\1\24\1\11\1\34\1\12\1\31\1\6"+
    "\1\0\1\46\2\0\1\11\1\0\1\22\1\25\1\32\1\21\1\20"+
    "\1\13\1\11\1\37\1\33\1\36\1\11\1\26\1\11\1\27\1\30"+
    "\1\40\1\35\1\15\1\23\1\17\1\24\1\11\1\34\1\12\1\31"+
    "\1\6\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\1\1\2\2\3\1\4\1\1"+
    "\1\5\2\1\6\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\3\0\2\3\10\0\5\5"+
    "\1\17\5\5\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\7\0\2\26\1\27\1\5\1\30\1\31\1\32\1\24"+
    "\7\0\1\33\1\5\1\24\1\34\1\35\2\0\1\36"+
    "\1\37\1\0\1\5\1\24\1\0\1\40\1\0\1\5"+
    "\1\24\1\41\1\0\1\42\1\24\1\0\1\24\1\43"+
    "\1\24";

  private static int [] zzUnpackAction() {
    int [] result = new int[105];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\116\0\165\0\234\0\303\0\352\0\u0111"+
    "\0\116\0\u0138\0\u015f\0\u0186\0\u01ad\0\u01d4\0\u01fb\0\u0222"+
    "\0\u0249\0\u0270\0\u0297\0\u015f\0\116\0\116\0\116\0\116"+
    "\0\116\0\u02be\0\116\0\u02e5\0\u030c\0\u0333\0\u0138\0\u035a"+
    "\0\116\0\u0381\0\u03a8\0\u03cf\0\u03f6\0\u041d\0\u0444\0\u046b"+
    "\0\u0492\0\u04b9\0\u04e0\0\u0507\0\u052e\0\u0555\0\u015f\0\u057c"+
    "\0\u05a3\0\u05ca\0\u05f1\0\u0618\0\116\0\116\0\116\0\116"+
    "\0\u063f\0\u0381\0\u0666\0\u068d\0\u06b4\0\u06db\0\u0702\0\u0729"+
    "\0\u0750\0\u0777\0\u015f\0\u015f\0\u079e\0\u015f\0\u015f\0\u015f"+
    "\0\u07c5\0\u07ec\0\u0813\0\u083a\0\u0861\0\u0888\0\u08af\0\u08d6"+
    "\0\u015f\0\u08fd\0\u0924\0\116\0\116\0\u094b\0\u0972\0\116"+
    "\0\116\0\u0999\0\u09c0\0\u09e7\0\u0a0e\0\116\0\u0a35\0\u0a5c"+
    "\0\u0a83\0\116\0\u0aaa\0\u015f\0\u0ad1\0\u0af8\0\u0b1f\0\116"+
    "\0\116";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[105];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\2\7\1\10\1\11\1\12"+
    "\3\13\1\14\1\13\1\15\3\13\1\16\1\17\1\13"+
    "\1\20\1\21\1\22\1\23\5\13\1\24\2\13\1\25"+
    "\1\26\1\27\1\30\1\31\1\3\4\32\2\3\37\32"+
    "\1\33\1\34\61\0\1\35\37\0\1\6\44\0\1\6"+
    "\1\0\1\6\47\0\4\7\1\36\37\0\1\13\1\0"+
    "\1\13\2\7\1\10\1\7\1\36\3\13\1\0\1\13"+
    "\1\0\22\13\6\0\4\37\1\40\2\41\40\37\1\0"+
    "\1\13\1\0\1\13\2\0\1\13\2\0\3\13\1\0"+
    "\1\13\1\0\22\13\23\0\1\42\50\0\1\43\1\0"+
    "\1\44\1\45\1\46\1\0\1\47\6\0\1\50\2\0"+
    "\1\51\10\0\1\13\1\0\1\13\2\0\1\13\2\0"+
    "\3\13\1\0\1\13\1\0\2\13\1\52\5\13\1\53"+
    "\11\13\7\0\1\13\1\0\1\13\2\0\1\13\2\0"+
    "\3\13\1\0\1\13\1\0\5\13\1\54\1\13\1\55"+
    "\2\13\1\56\2\13\1\57\4\13\7\0\1\13\1\0"+
    "\1\13\2\0\1\13\2\0\3\13\1\0\1\13\1\0"+
    "\1\13\1\60\6\13\1\61\11\13\7\0\1\13\1\0"+
    "\1\13\2\0\1\13\2\0\3\13\1\0\1\13\1\0"+
    "\5\13\1\62\7\13\1\57\4\13\7\0\1\13\1\0"+
    "\1\13\2\0\1\13\2\0\3\13\1\0\1\13\1\0"+
    "\11\13\1\63\10\13\7\0\1\13\1\0\1\13\2\0"+
    "\1\13\2\0\3\13\1\0\1\64\1\0\22\13\6\0"+
    "\4\32\2\0\37\32\17\0\1\65\1\0\1\66\7\0"+
    "\1\67\15\0\1\70\2\0\1\71\1\0\1\71\7\0"+
    "\1\71\4\0\3\71\2\0\1\71\4\0\1\71\14\0"+
    "\4\36\3\7\40\36\5\0\1\41\42\0\1\72\1\0"+
    "\1\72\63\0\1\73\50\0\1\74\47\0\1\75\63\0"+
    "\1\76\37\0\1\77\45\0\1\100\40\0\1\101\25\0"+
    "\1\13\1\0\1\13\2\0\1\13\2\0\3\13\1\0"+
    "\1\13\1\0\2\13\1\102\17\13\7\0\1\13\1\0"+
    "\1\13\2\0\1\13\2\0\3\13\1\0\1\13\1\0"+
    "\2\13\1\103\17\13\7\0\1\13\1\0\1\13\2\0"+
    "\1\13\2\0\3\13\1\0\1\13\1\0\6\13\1\103"+
    "\13\13\7\0\1\13\1\0\1\13\2\0\1\13\2\0"+
    "\3\13\1\0\1\13\1\0\1\103\6\13\1\104\12\13"+
    "\7\0\1\13\1\0\1\13\2\0\1\13\2\0\3\13"+
    "\1\0\1\13\1\0\4\13\1\105\15\13\7\0\1\13"+
    "\1\0\1\13\2\0\1\13\2\0\3\13\1\0\1\13"+
    "\1\0\16\13\1\106\3\13\7\0\1\13\1\0\1\13"+
    "\2\0\1\13\2\0\3\13\1\0\1\13\1\0\1\13"+
    "\1\106\20\13\7\0\1\13\1\0\1\13\2\0\1\13"+
    "\2\0\3\13\1\0\1\13\1\0\14\13\1\107\5\13"+
    "\7\0\1\13\1\0\1\13\2\0\1\13\2\0\3\13"+
    "\1\0\1\103\1\0\22\13\7\0\1\13\1\0\1\13"+
    "\2\0\1\13\2\0\3\13\1\0\1\13\1\0\14\13"+
    "\1\110\5\13\7\0\1\111\1\0\1\111\7\0\1\111"+
    "\4\0\3\111\2\0\1\111\4\0\1\111\26\0\1\112"+
    "\53\0\1\113\61\0\1\114\36\0\1\115\43\0\1\116"+
    "\44\0\1\117\57\0\1\120\21\0\1\13\1\0\1\13"+
    "\2\0\1\13\2\0\3\13\1\0\1\13\1\0\14\13"+
    "\1\121\5\13\7\0\1\13\1\0\1\13\2\0\1\13"+
    "\2\0\3\13\1\0\1\13\1\0\13\13\1\122\6\13"+
    "\7\0\1\123\1\0\1\123\7\0\1\123\4\0\3\123"+
    "\2\0\1\123\4\0\1\123\33\0\1\124\51\0\1\125"+
    "\57\0\1\126\45\0\1\127\34\0\1\130\47\0\1\131"+
    "\40\0\1\132\34\0\1\13\1\0\1\13\2\0\1\13"+
    "\2\0\3\13\1\0\1\13\1\0\3\13\1\133\16\13"+
    "\7\0\1\134\1\0\1\134\7\0\1\134\4\0\3\134"+
    "\2\0\1\134\4\0\1\134\47\0\1\135\33\0\1\136"+
    "\62\0\1\137\13\0\1\13\1\0\1\13\2\0\1\13"+
    "\2\0\3\13\1\0\1\13\1\0\7\13\1\140\12\13"+
    "\7\0\1\141\1\0\1\141\7\0\1\141\4\0\3\141"+
    "\2\0\1\141\4\0\1\141\22\0\1\142\70\0\1\143"+
    "\17\0\1\13\1\0\1\13\2\0\1\13\2\0\3\13"+
    "\1\0\1\13\1\0\7\13\1\144\12\13\7\0\1\145"+
    "\1\0\1\145\7\0\1\145\4\0\3\145\2\0\1\145"+
    "\4\0\1\145\31\0\1\146\32\0\1\147\1\0\1\147"+
    "\7\0\1\147\4\0\3\147\2\0\1\147\4\0\1\147"+
    "\35\0\1\150\26\0\1\151\1\0\1\151\7\0\1\151"+
    "\4\0\3\151\2\0\1\151\4\0\1\151\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2886];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\5\1\1\11\13\1\5\11\1\1\1\11"+
    "\1\1\3\0\1\1\1\11\10\0\13\1\4\11\2\1"+
    "\7\0\10\1\7\0\3\1\2\11\2\0\2\11\1\0"+
    "\2\1\1\0\1\11\1\0\2\1\1\11\1\0\2\1"+
    "\1\0\1\1\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[105];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private static final boolean DEBUG = false;
    private StringBuffer string = new StringBuffer();
    private void error(String message) {
        System.err.println( "Error at line " + (yyline+1) +
                            ", col " + (yycolumn+1) +
                            " : " + message );
    }

    private void debugSymbols( int t, int l, int c, Object o ) {
        if( DEBUG ) {
        String str = Integer.toString( t );

        System.err.print( "Returning symbol:" + str );
        System.err.print( " line: " + (l+1) );
        System.err.print( " col: " + (c+1) );
        if( o != null ) {
            System.err.print( " o: " + o.toString() );
        }
        System.err.println();
        }
    }

    private Symbol symbol(int type) {
        debugSymbols( type, yyline, yycolumn, null );
        return new Symbol(type, yyline, yycolumn);
    }

    private Symbol symbol(int type, Object value) {
        debugSymbols( type, yyline, yycolumn, value );
        return new Symbol(type, yyline, yycolumn, value);
    }

    private Long convertToValid32I( String str, int base ) {
        long num = Long.parseLong( str, base );
        Long ret = null;

        if( num > Integer.MAX_VALUE || num > 4294967295L ) {
            error( str + " cannot be represented by the word size (32-bits)." +
                   "Maximum value allowed is " + 4294967295L );
        } else if( num < Integer.MIN_VALUE ) {
            error( str + " cannot be represented by the word size (32-bits)." +
                   "Minimum value allowed is " + Integer.MIN_VALUE );
        } else {
            ret = new Long( num );
        }

        return ret;
    }

    private Integer convertToValidReg( String str ) {
        int r = Integer.parseInt( str );
        Integer ret = null;
        if( r > 31 ) {
            error( str + " is not a valid register. Too large." );
        } else {
            ret = new Integer( r );
        }
        return ret;
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  MipsLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  MipsLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 164) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 18: 
          { string.append('\n');
          }
        case 36: break;
        case 7: 
          { return symbol( sym.COMMA );
          }
        case 37: break;
        case 6: 
          { return symbol( sym.JOPER, yytext() );
          }
        case 38: break;
        case 8: 
          { return symbol( sym.COLON );
          }
        case 39: break;
        case 10: 
          { return symbol( sym.RPAREN );
          }
        case 40: break;
        case 32: 
          { return symbol( sym.DSPACE );
          }
        case 41: break;
        case 12: 
          { string.append( yytext() );
          }
        case 42: break;
        case 29: 
          { return symbol( sym.STARTDATA );
          }
        case 43: break;
        case 3: 
          { if (DEBUG) System.err.println( "EOL match: < " + yytext() + " >" ); return symbol( sym.EOL );
          }
        case 44: break;
        case 5: 
          { return symbol( sym.LABEL, yytext() );
          }
        case 45: break;
        case 23: 
          { return symbol( sym.RSOPER, yytext() );
          }
        case 46: break;
        case 4: 
          { /* IGNORE */ if( DEBUG) System.err.println("Ignoreing Space! <" +yytext()+ ">");
          }
        case 47: break;
        case 30: 
          { return symbol( sym.DBYTE );
          }
        case 48: break;
        case 14: 
          { string.append('\\');
          }
        case 49: break;
        case 22: 
          { return symbol( sym.ROPER, yytext() );
          }
        case 50: break;
        case 11: 
          { string.setLength(0); yybegin(STRING);
          }
        case 51: break;
        case 28: 
          { return symbol( sym.STARTTEXT );
          }
        case 52: break;
        case 34: 
          { return symbol( sym.SYSCALL );
          }
        case 53: break;
        case 26: 
          { return symbol( sym.ILABELOPER, yytext() );
          }
        case 54: break;
        case 33: 
          { return symbol( sym.DASCIIZ );
          }
        case 55: break;
        case 16: 
          { string.append('\r');
          }
        case 56: break;
        case 15: 
          { return symbol( sym.IMEMOPER, yytext() );
          }
        case 57: break;
        case 21: 
          { Integer r = convertToValidReg( yytext().substring(2) ); 
                                if( r != null ) return symbol( sym.REG, r );
                                else throw new Error( "Lexer failed due to invalid register specification." );
          }
        case 58: break;
        case 27: 
          { return symbol( sym.IOPER, yytext() );
          }
        case 59: break;
        case 19: 
          { string.append('\"');
          }
        case 60: break;
        case 9: 
          { return symbol( sym.LPAREN );
          }
        case 61: break;
        case 1: 
          { error( "Unknown token! Did you accidentally a letter?" );
                                throw new Error("Illegal character <"+yytext()+">");
          }
        case 62: break;
        case 31: 
          { return symbol( sym.DWORD );
          }
        case 63: break;
        case 25: 
          { return symbol( sym.ISINGREGOP, yytext() );
          }
        case 64: break;
        case 20: 
          { Long val = convertToValid32I( yytext().substring(2), 16 );
                                if( val != null ) return symbol( sym.IMM, val );
                                else throw new Error( "Lexer failed due to bad integer value." );
          }
        case 65: break;
        case 13: 
          { yybegin(YYINITIAL); 
                                   return symbol(sym.STRLITERAL, 
                                   string.toString());
          }
        case 66: break;
        case 2: 
          { Long val = convertToValid32I( yytext(), 10 );
                                if( val != null ) return symbol( sym.IMM, val );
                                else throw new Error( "Lexer failed due to bad integer value." );
          }
        case 67: break;
        case 35: 
          { return symbol( sym.DHALFWORD );
          }
        case 68: break;
        case 24: 
          { return symbol( sym.IBRANCHOP, yytext() );
          }
        case 69: break;
        case 17: 
          { string.append('\t');
          }
        case 70: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
