
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 12 22:07:56 EDT 2012
//----------------------------------------------------

import java_cup.runtime.Symbol;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Fri Oct 12 22:07:56 EDT 2012
  */
public class MipsParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public MipsParser() {super();}

  /** Constructor which sets the default scanner. */
  public MipsParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public MipsParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\007\000\002\002\004\000\002\002\004\000\002\004" +
    "\002\000\002\003\004\000\002\005\004\000\002\006\007" +
    "\000\002\006\007" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\022\000\004\005\uffff\001\002\000\004\002\024\001" +
    "\002\000\004\005\006\001\002\000\002\001\002\000\004" +
    "\002\000\001\002\000\010\002\ufffe\006\011\007\012\001" +
    "\002\000\004\010\020\001\002\000\004\010\014\001\002" +
    "\000\010\002\ufffd\006\ufffd\007\ufffd\001\002\000\004\010" +
    "\015\001\002\000\004\011\016\001\002\000\004\004\017" +
    "\001\002\000\010\002\ufffb\006\ufffb\007\ufffb\001\002\000" +
    "\004\010\021\001\002\000\004\010\022\001\002\000\004" +
    "\004\023\001\002\000\010\002\ufffc\006\ufffc\007\ufffc\001" +
    "\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\022\000\006\002\003\004\004\001\001\000\002\001" +
    "\001\000\004\003\006\001\001\000\004\005\007\001\001" +
    "\000\002\001\001\000\004\006\012\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$MipsParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$MipsParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$MipsParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {
 RESULT = new AbstractSyntax(); 
    }
}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$MipsParser$actions {
  private final MipsParser parser;

  /** Constructor */
  CUP$MipsParser$actions(MipsParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$MipsParser$do_action(
    int                        CUP$MipsParser$act_num,
    java_cup.runtime.lr_parser CUP$MipsParser$parser,
    java.util.Stack            CUP$MipsParser$stack,
    int                        CUP$MipsParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$MipsParser$result;

      /* select the action based on the action number */
      switch (CUP$MipsParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // rinst ::= RSOPER REG REG INT EOL 
            {
              Object RESULT =null;
		int opleft = ((java_cup.runtime.Symbol)CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-4)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-4)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-4)).value;
		int rdleft = ((java_cup.runtime.Symbol)CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-3)).left;
		int rdright = ((java_cup.runtime.Symbol)CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-3)).right;
		Integer rd = (Integer)((java_cup.runtime.Symbol) CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-3)).value;
		int rtleft = ((java_cup.runtime.Symbol)CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-2)).left;
		int rtright = ((java_cup.runtime.Symbol)CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-2)).right;
		Integer rt = (Integer)((java_cup.runtime.Symbol) CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-2)).value;
		int shamtleft = ((java_cup.runtime.Symbol)CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-1)).left;
		int shamtright = ((java_cup.runtime.Symbol)CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-1)).right;
		Long shamt = (Long)((java_cup.runtime.Symbol) CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-1)).value;

              CUP$MipsParser$result = parser.getSymbolFactory().newSymbol("rinst",4, ((java_cup.runtime.Symbol)CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-4)), ((java_cup.runtime.Symbol)CUP$MipsParser$stack.peek()), RESULT);
            }
          return CUP$MipsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // rinst ::= ROPER REG REG REG EOL 
            {
              Object RESULT =null;
		int opleft = ((java_cup.runtime.Symbol)CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-4)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-4)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-4)).value;
		int rdleft = ((java_cup.runtime.Symbol)CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-3)).left;
		int rdright = ((java_cup.runtime.Symbol)CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-3)).right;
		Integer rd = (Integer)((java_cup.runtime.Symbol) CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-3)).value;
		int rsleft = ((java_cup.runtime.Symbol)CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-2)).left;
		int rsright = ((java_cup.runtime.Symbol)CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-2)).right;
		Integer rs = (Integer)((java_cup.runtime.Symbol) CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-2)).value;
		int rtleft = ((java_cup.runtime.Symbol)CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-1)).left;
		int rtright = ((java_cup.runtime.Symbol)CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-1)).right;
		Integer rt = (Integer)((java_cup.runtime.Symbol) CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-1)).value;

              CUP$MipsParser$result = parser.getSymbolFactory().newSymbol("rinst",4, ((java_cup.runtime.Symbol)CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-4)), ((java_cup.runtime.Symbol)CUP$MipsParser$stack.peek()), RESULT);
            }
          return CUP$MipsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // instructions ::= instructions rinst 
            {
              Object RESULT =null;

              CUP$MipsParser$result = parser.getSymbolFactory().newSymbol("instructions",3, ((java_cup.runtime.Symbol)CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-1)), ((java_cup.runtime.Symbol)CUP$MipsParser$stack.peek()), RESULT);
            }
          return CUP$MipsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // textsection ::= STARTTEXT instructions 
            {
              Object RESULT =null;

              CUP$MipsParser$result = parser.getSymbolFactory().newSymbol("textsection",1, ((java_cup.runtime.Symbol)CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-1)), ((java_cup.runtime.Symbol)CUP$MipsParser$stack.peek()), RESULT);
            }
          return CUP$MipsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // datasection ::= 
            {
              Object RESULT =null;

              CUP$MipsParser$result = parser.getSymbolFactory().newSymbol("datasection",2, ((java_cup.runtime.Symbol)CUP$MipsParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$MipsParser$stack.peek()), RESULT);
            }
          return CUP$MipsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= datasection textsection 
            {
              Object RESULT =null;

              CUP$MipsParser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-1)), ((java_cup.runtime.Symbol)CUP$MipsParser$stack.peek()), RESULT);
            }
          return CUP$MipsParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-1)).value;
		RESULT = start_val;
              CUP$MipsParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$MipsParser$stack.elementAt(CUP$MipsParser$top-1)), ((java_cup.runtime.Symbol)CUP$MipsParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$MipsParser$parser.done_parsing();
          return CUP$MipsParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

