/* The following code was generated by JFlex 1.4.3 on 10/14/12 8:07 PM */

import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 10/14/12 8:07 PM from the specification file
 * <tt>MipsLexer.flex</tt>
 */
class MipsLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\11\1\7\1\0\1\11\1\6\22\0\1\11\2\0\1\12"+
    "\1\14\3\0\1\37\1\40\2\0\1\35\1\2\1\16\1\0\1\1"+
    "\11\3\1\36\6\0\1\22\1\25\1\5\1\21\1\20\1\5\2\13"+
    "\1\31\1\34\1\13\1\26\1\13\1\27\1\30\1\13\1\33\1\15"+
    "\1\23\1\17\1\24\1\13\1\32\1\4\1\13\1\10\4\0\1\13"+
    "\1\0\1\22\1\25\1\5\1\21\1\20\1\5\2\13\1\31\1\34"+
    "\1\13\1\26\1\13\1\27\1\30\1\13\1\33\1\15\1\23\1\17"+
    "\1\24\1\13\1\32\1\4\1\13\1\10\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\2\1\3\2\4\1\5"+
    "\3\1\6\3\1\6\1\7\1\10\1\11\1\12\3\0"+
    "\2\4\3\0\4\3\1\13\5\3\1\14\1\15\2\0"+
    "\2\16\1\17\1\20\1\21\1\22\1\14\2\0\1\23"+
    "\1\14\1\24\1\25\5\14";

  private static int [] zzUnpackAction() {
    int [] result = new int[63];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\41\0\102\0\143\0\204\0\245\0\306\0\347"+
    "\0\41\0\u0108\0\u0129\0\u014a\0\u016b\0\u018c\0\u01ad\0\u01ce"+
    "\0\u01ef\0\u0210\0\245\0\41\0\41\0\41\0\41\0\u0231"+
    "\0\u0252\0\u0108\0\u0273\0\41\0\u0294\0\u02b5\0\u02d6\0\u02f7"+
    "\0\u0318\0\u0339\0\u035a\0\245\0\u037b\0\u039c\0\u03bd\0\u03de"+
    "\0\u03ff\0\u0420\0\u0294\0\u0441\0\u0462\0\u0483\0\245\0\245"+
    "\0\245\0\245\0\245\0\u04a4\0\u04c5\0\u04e6\0\245\0\u0507"+
    "\0\41\0\41\0\u0528\0\u0549\0\u056a\0\u058b\0\41";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[63];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\2\6\2\7\1\10\1\11"+
    "\1\12\1\6\1\13\1\6\1\14\3\6\1\15\1\16"+
    "\1\6\1\17\1\20\1\21\1\22\3\6\1\23\1\24"+
    "\1\25\1\26\1\27\45\0\1\30\37\0\1\5\36\0"+
    "\1\5\1\0\1\5\36\0\1\6\1\0\3\6\2\0"+
    "\1\6\2\0\1\6\1\0\1\6\1\0\16\6\12\0"+
    "\4\7\1\31\27\0\1\6\1\0\3\6\2\7\1\10"+
    "\1\7\1\31\1\6\1\0\1\6\1\0\16\6\4\0"+
    "\6\32\1\33\2\34\30\32\15\0\1\35\42\0\1\36"+
    "\1\0\1\37\20\0\1\6\1\0\3\6\2\0\1\6"+
    "\2\0\1\6\1\0\1\6\1\0\2\6\1\40\5\6"+
    "\1\41\5\6\5\0\1\6\1\0\3\6\2\0\1\6"+
    "\2\0\1\6\1\0\1\6\1\0\5\6\1\42\1\6"+
    "\1\43\3\6\1\44\2\6\5\0\1\6\1\0\3\6"+
    "\2\0\1\6\2\0\1\6\1\0\1\6\1\0\1\6"+
    "\1\45\6\6\1\46\5\6\5\0\1\6\1\0\3\6"+
    "\2\0\1\6\2\0\1\6\1\0\1\6\1\0\5\6"+
    "\1\47\5\6\1\44\2\6\5\0\1\6\1\0\3\6"+
    "\2\0\1\6\2\0\1\6\1\0\1\6\1\0\11\6"+
    "\1\50\4\6\5\0\1\6\1\0\3\6\2\0\1\6"+
    "\2\0\1\6\1\0\1\51\1\0\16\6\5\0\1\52"+
    "\1\0\1\52\1\0\1\52\12\0\3\52\2\0\1\52"+
    "\13\0\6\31\3\7\30\31\7\0\1\34\32\0\1\53"+
    "\1\0\1\53\55\0\1\54\42\0\1\55\17\0\1\6"+
    "\1\0\3\6\2\0\1\6\2\0\1\6\1\0\1\6"+
    "\1\0\2\6\1\56\13\6\5\0\1\6\1\0\3\6"+
    "\2\0\1\6\2\0\1\6\1\0\1\6\1\0\2\6"+
    "\1\57\13\6\5\0\1\6\1\0\3\6\2\0\1\6"+
    "\2\0\1\6\1\0\1\6\1\0\6\6\1\57\7\6"+
    "\5\0\1\6\1\0\3\6\2\0\1\6\2\0\1\6"+
    "\1\0\1\6\1\0\1\57\6\6\1\60\6\6\5\0"+
    "\1\6\1\0\3\6\2\0\1\6\2\0\1\6\1\0"+
    "\1\6\1\0\14\6\1\61\1\6\5\0\1\6\1\0"+
    "\3\6\2\0\1\6\2\0\1\6\1\0\1\6\1\0"+
    "\1\6\1\61\14\6\5\0\1\6\1\0\3\6\2\0"+
    "\1\6\2\0\1\6\1\0\1\6\1\0\12\6\1\62"+
    "\3\6\5\0\1\6\1\0\3\6\2\0\1\6\2\0"+
    "\1\6\1\0\1\57\1\0\16\6\5\0\1\6\1\0"+
    "\3\6\2\0\1\6\2\0\1\6\1\0\1\6\1\0"+
    "\12\6\1\63\3\6\5\0\1\64\1\0\1\64\1\0"+
    "\1\64\12\0\3\64\2\0\1\64\17\0\1\65\53\0"+
    "\1\66\22\0\1\6\1\0\3\6\2\0\1\6\2\0"+
    "\1\6\1\0\1\6\1\0\12\6\1\67\3\6\5\0"+
    "\1\70\1\0\1\70\1\0\1\70\12\0\3\70\2\0"+
    "\1\70\32\0\1\71\43\0\1\72\17\0\1\73\1\0"+
    "\1\73\1\0\1\73\12\0\3\73\2\0\1\73\14\0"+
    "\1\74\1\0\1\74\1\0\1\74\12\0\3\74\2\0"+
    "\1\74\14\0\1\75\1\0\1\75\1\0\1\75\12\0"+
    "\3\75\2\0\1\75\14\0\1\76\1\0\1\76\1\0"+
    "\1\76\12\0\3\76\2\0\1\76\14\0\1\77\1\0"+
    "\1\77\1\0\1\77\12\0\3\77\2\0\1\77\13\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1452];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\6\1\1\11\12\1\4\11\3\0\1\1"+
    "\1\11\3\0\14\1\2\0\7\1\2\0\2\1\2\11"+
    "\4\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[63];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private static final boolean DEBUG = false;
    private void error(String message) {
        System.err.println( "Error at line " + (yyline+1) +
                            ", col " + (yycolumn+1) +
                            " : " + message );
    }

    private void debugSymbols( int t, int l, int c, Object o ) {
        String str;
        switch ( t ) {
   case 13: str = "IMEMOPER"; break;
   case 16: str = "ISINGREGOP"; break;
   case 8: str = "RPAREN"; break;
   case 6: str = "STARTTEXT"; break;
   case 17: str = "REG"; break;
   case 10: str = "ROPER"; break;
   case 7: str = "LPAREN"; break;
   case 4: str = "COLON"; break;
   case 2: str = "EOL"; break;
   case 3: str = "COMMA"; break;
   case 14: str = "ILABELOPER"; break;
   case 0: str = "EOF"; break;
   case 15: str = "IBRANCHOP"; break;
   case 1: str = "error"; break;
   case 5: str = "STARTDATA"; break;
   case 12: str = "IOPER"; break;
   case 11: str = "RSOPER"; break;
   case 18: str = "IMM"; break;
   case 9: str = "LABEL"; break;
         default: str = Integer.toString( t ); break;
         }

        System.err.print( "Returning symbol:" + str );
        System.err.print( " line: " + (l+1) );
        System.err.print( " col: " + (c+1) );
        if( o != null ) {
            System.err.print( " o: " + o.toString() );
        }
        System.err.println();
    }

    private Symbol symbol(int type) {
        debugSymbols( type, yyline, yycolumn, null );
        return new Symbol(type, yyline, yycolumn);
    }

    private Symbol symbol(int type, Object value) {
        debugSymbols( type, yyline, yycolumn, value );
        return new Symbol(type, yyline, yycolumn, value);
    }

    private Integer convertToValid32I( String str, int base ) {
        long num = Long.parseLong( str, base );
        Integer ret = null;

        if( num > Integer.MAX_VALUE || num > 4294967295L ) {
            error( str + " cannot be represented by the word size (32-bits)." +
                   "Maximum value allowed is " + 4294967295L );
        } else if( num < Integer.MIN_VALUE ) {
            error( str + " cannot be represented by the word size (32-bits)." +
                   "Minimum value allowed is " + Integer.MIN_VALUE );
        } else {
            ret = new Integer( (int)num );
        }

        return ret;
    }

    private Integer convertToValidReg( String str ) {
        int r = Integer.parseInt( str );
        Integer ret = null;
        if( r > 31 ) {
            error( str + " is not a valid register. Too large." );
        } else {
            ret = new Integer( r );
        }
        return ret;
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  MipsLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  MipsLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 154) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 7: 
          { return symbol( sym.COMMA );
          }
        case 22: break;
        case 6: 
          { return symbol( sym.JOPER, yytext() );
          }
        case 23: break;
        case 12: 
          { Integer val = convertToValid32I( yytext().substring(2), 16 );
                                if( val != null ) return symbol( sym.IMM, val );
                                else throw new Error( "Lexer failed due to bad integer value." );
          }
        case 24: break;
        case 8: 
          { return symbol( sym.COLON );
          }
        case 25: break;
        case 10: 
          { return symbol( sym.RPAREN );
          }
        case 26: break;
        case 21: 
          { return symbol( sym.STARTDATA );
          }
        case 27: break;
        case 2: 
          { Integer val = convertToValid32I( yytext(), 10 );
                                if( val != null ) return symbol( sym.IMM, val );
                                else throw new Error( "Lexer failed due to bad integer value." );
          }
        case 28: break;
        case 4: 
          { if (DEBUG) System.err.println( "EOL match: < " + yytext() + " >" ); return symbol( sym.EOL );
          }
        case 29: break;
        case 3: 
          { return symbol( sym.LABEL, yytext() );
          }
        case 30: break;
        case 5: 
          { /* IGNORE */ if( DEBUG) System.err.println("Ignoreing Space! <" +yytext()+ ">");
          }
        case 31: break;
        case 15: 
          { return symbol( sym.RSOPER, yytext() );
          }
        case 32: break;
        case 14: 
          { return symbol( sym.ROPER, yytext() );
          }
        case 33: break;
        case 20: 
          { return symbol( sym.STARTTEXT );
          }
        case 34: break;
        case 18: 
          { return symbol( sym.ILABELOPER, yytext() );
          }
        case 35: break;
        case 11: 
          { return symbol( sym.IMEMOPER, yytext() );
          }
        case 36: break;
        case 13: 
          { Integer r = convertToValidReg( yytext().substring(2) ); 
                                if( r != null ) return symbol( sym.REG, r );
                                else throw new Error( "Lexer failed due to invalid register specification." );
          }
        case 37: break;
        case 19: 
          { return symbol( sym.IOPER, yytext() );
          }
        case 38: break;
        case 9: 
          { return symbol( sym.LPAREN );
          }
        case 39: break;
        case 1: 
          { error( "Unknown token! Did you accidentally a letter?" );
                                throw new Error("Illegal character <"+yytext()+">");
          }
        case 40: break;
        case 17: 
          { return symbol( sym.ISINGREGOP, yytext() );
          }
        case 41: break;
        case 16: 
          { return symbol( sym.IBRANCHOP, yytext() );
          }
        case 42: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
