
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 12 22:07:56 EDT 2012
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ROPER = 4;
  public static final int REG = 6;
  public static final int EOL = 2;
  public static final int error = 1;
  public static final int RSOPER = 5;
  public static final int STARTTEXT = 3;
  public static final int EOF = 0;
  public static final int INT = 7;
}

